##########################################
#
# Homo DeUS Pose data
#
##########################################

#####################
# Goal id
#####################
homodeus_msgs/DesireID id
#####################
# Goal place name
#####################
std_msgs/String name
#####################
# Goal pose (position.x -> x [m], position.y -> y [m],
#            orientation.z -> angle plan xy [rad])
#####################
geometry_msgs/Pose pose
